_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 103
            "2":
                - 1
                - 9
                - 41
                - 55
                - 103
            "3":
                - 2
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.3
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": darwin-arm64
learning_rate:
    value: 0.001
neurons_fc1:
    value: 1024
neurons_fc2:
    value: 128
optimizer:
    value: sgd
